os: linux
dist: xenial
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

services:
  - redis-server

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  # --prefer-source for including test directory for amphp/cache
  - composer update -n --prefer-source
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

  - composer show

script:
  - AMPHP_TEST_REDIS_INSTANCE=tcp://localhost:6379 phpdbg -qrr vendor/bin/phpunit --verbose --coverage-php coverage/cov/main.cov
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
  - travis_retry php php-coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local
